[package]
name = "tests"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.9.1"
solana-sdk = "1.9.1"
hex = "0.4"
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
